### ISSUE TITLE
Test suite fails if Date::Manip is installed

### ISSUE THREAD

**Issue by eserte** [pjcj/Gedcom.pm#5] opened 2015-02-21 15:01 UTC
There is a number of mysterious test failures with Gedcom-1.19 (see http://matrix.cpantesters.org/?dist=Gedcom+1.19 ) and http://analysis.cpantesters.org/solved?distv=Gedcom-1.19 does not seem to find the reason for these failures. My guess is that the test suite is failing only if Date::Manip is installed.

**Comment by pjcj** [comment] 2015-02-22 18:13
Ouch.  I'll try to repeat this and track it down.  Thanks for noticing and reporting it!

++ to the CPAN testing infrastructure.

**Comment by ntyni** [comment] 2015-09-21 19:17
FYI, this goes away if the test suite is run with DATE_MANIP=DM5 in the environment. I see this enables an older Date::Manip interface that is no longer maintained.

**Comment by gregoa** [comment] 2015-12-26 02:24
Some findings:

* GEDCOM seems to support some interesting date definitions, cf. http://wiki-en.genealogy.net/GEDCOM/DATE-Tag, eg. AFT yyyy (for "after year xx") or ABT yyyy for approximate dates
* The test failures (well, at least most of them) seem to be caused by normalise_dates() in lib/Gedcom/Record.pm which uses Date::Manip's ParseDate() routine.
* This seems to have changed between 5 and 6; in v5 it seems to fail on 'AFT    1989', so normalise_dates() just returns the original value, in v6 it does something with it.
* In v6 ParseDate() can be passed an array of Date::Manip::Date::parse options. When I (wild guessingly) use the following in normalise_dates(), all but on test failures go away (as ParseDate() doesn't (mis)interpret 'AFT    1989' -- as a whatever):

```
          my $date = ParseDate($dt, qw/nodelta/);
```
* One failure still remains:
```
Test Summary Report
-------------------
t/parse_grammar.t    (Wstat: 0 Tests: 1504 Failed: 1)
  Failed test:  1466
Files=15, Tests=9439,  7 wallclock secs ( 0.93 usr  0.11 sys +  5.33 cusr  0.24 csys =  6.61 CPU)
Result: FAIL
```

Not sure what this all tells us; my gut feeling is that passing funny GEDCOM dates to Date::Manip is a bit brittle; maybe they should be filtered out before, or maybe ParseDate and friends can be taught to ignore them.

Cheers,
gregor

**Comment by intrigeri** [comment] 2016-06-26 13:40
Dear Maintainer,

The Debian perl group is reviewing packages with bugs which make them un-releasable; in particular when they are not heavily used by Debian users. We would like to remove such modules from Debian if we don't think they are likely to be fixed.

Gedcom.pm is one such module, owing to this bug, and we would like to know whether you have any plans to look at the bug in the foreseeable future before we remove the package from Debian.

If we don't hear anything we will remove the package from Debian on or around 2016-09-26. This of course does not affect the standing of your module on CPAN.

Thank you for maintaining this module so far!

**Comment by pjcj** [comment] 2016-09-09 21:46
Thanks to everyone for the report, the analysis and the tips for fixing.  As of 9c432910b1a93349f3b2a35f6f59438ee369e910 the tests are all passing for me with Date::Manip 6.55 and without Date::Manip.  This fix will be in the next release.

**Closed by pjcj** 2016-09-09 21:46 UTC

**Comment by pjcj** [comment] 2016-09-18 20:27
Version 1.20 is now released and seems to be passing all tests:  http://matrix.cpantesters.org/?dist=Gedcom%201.20

Thanks again to all involved.
